<?php

declare(strict_types=1);

namespace Gameism\Game;

final class GameCatalog
{
    /**
     * @return array<string,array<string,mixed>>
     */
    public static function controls(): array
    {
        return [
            'documented_owner' => [
                'label' => 'Documented owner',
                'description' => 'A responsible person is named for this asset or process.',
                'categories' => ['documentation' => 2, 'audit' => 2],
                'severity' => 'minor',
                'finding' => 'Asset ownership is not documented.',
                'recommendation' => 'Assign and record an owner so maintenance and evidence requests have accountability.',
            ],
            'mfa_enabled' => [
                'label' => 'MFA enabled',
                'description' => 'Interactive access requires a second factor.',
                'categories' => ['security' => 3, 'audit' => 1],
                'severity' => 'major',
                'finding' => 'Access is protected by password only.',
                'recommendation' => 'Enable MFA for staff accounts and keep enrollment evidence.',
            ],
            'disk_encryption' => [
                'label' => 'Disk encryption',
                'description' => 'Local storage is encrypted to reduce exposure after theft or loss.',
                'categories' => ['security' => 3, 'resilience' => 1],
                'severity' => 'major',
                'finding' => 'Endpoint storage is not protected by full-disk encryption.',
                'recommendation' => 'Enable full-disk encryption and record device compliance status.',
            ],
            'patching_current' => [
                'label' => 'Patching current',
                'description' => 'Operating system, browser, and critical applications are current.',
                'categories' => ['security' => 3, 'resilience' => 1],
                'severity' => 'major',
                'finding' => 'Patch status is not current.',
                'recommendation' => 'Apply updates and define a recurring patch review process.',
            ],
            'screen_lock' => [
                'label' => 'Auto screen lock',
                'description' => 'Sessions lock automatically after short inactivity.',
                'categories' => ['security' => 2],
                'severity' => 'minor',
                'finding' => 'The workstation can remain unlocked when unattended.',
                'recommendation' => 'Set automatic session locking and verify it on shared work areas.',
            ],
            'least_privilege' => [
                'label' => 'Least privilege',
                'description' => 'Users do not have unnecessary local or application admin rights.',
                'categories' => ['security' => 3, 'audit' => 1],
                'severity' => 'major',
                'finding' => 'Users may have broader privileges than needed.',
                'recommendation' => 'Remove unnecessary admin rights and document privileged access approval.',
            ],
            'supplier_reviewed' => [
                'label' => 'Supplier reviewed',
                'description' => 'The cloud or service provider has been assessed for security and continuity.',
                'categories' => ['documentation' => 2, 'audit' => 2, 'resilience' => 1],
                'severity' => 'major',
                'finding' => 'Supplier risk has not been assessed.',
                'recommendation' => 'Record supplier security, continuity, and support review evidence.',
            ],
            'contract_dpa' => [
                'label' => 'Contract and DPA',
                'description' => 'Contractual security and data processing terms are available.',
                'categories' => ['documentation' => 2, 'audit' => 2],
                'severity' => 'major',
                'finding' => 'Supplier contract evidence is incomplete.',
                'recommendation' => 'Keep contract, data processing, and security commitments available for audit.',
            ],
            'access_review' => [
                'label' => 'Access review',
                'description' => 'User access is reviewed and stale accounts are removed.',
                'categories' => ['security' => 2, 'documentation' => 1, 'audit' => 2],
                'severity' => 'major',
                'finding' => 'There is no recent access review evidence.',
                'recommendation' => 'Review user access periodically and keep the review record.',
            ],
            'backup_export_plan' => [
                'label' => 'Export and exit plan',
                'description' => 'Critical cloud data can be exported or recovered if the service is unavailable.',
                'categories' => ['resilience' => 3, 'documentation' => 1],
                'severity' => 'major',
                'finding' => 'No practical cloud data export or exit plan is documented.',
                'recommendation' => 'Define how patient and business data can be exported, restored, or migrated.',
            ],
            'secure_print' => [
                'label' => 'Secure print',
                'description' => 'Print jobs require release by an authorized staff member.',
                'categories' => ['security' => 2],
                'severity' => 'minor',
                'finding' => 'Printed patient information can remain exposed at the printer.',
                'recommendation' => 'Enable secure release or move printing into a supervised workflow.',
            ],
            'located_supervised' => [
                'label' => 'Supervised location',
                'description' => 'The device is placed where unauthorized access is unlikely.',
                'categories' => ['security' => 1],
                'severity' => 'minor',
                'finding' => 'The device location is weak for confidentiality.',
                'recommendation' => 'Place the device in a supervised area or add compensating controls.',
            ],
            'disposal_procedure' => [
                'label' => 'Disposal procedure',
                'description' => 'Sensitive paper or media disposal is defined and followed.',
                'categories' => ['security' => 1, 'documentation' => 2, 'audit' => 1],
                'severity' => 'minor',
                'finding' => 'Sensitive disposal is not defined.',
                'recommendation' => 'Document shredding or secure disposal steps and staff responsibilities.',
            ],
            'admin_password_changed' => [
                'label' => 'Admin password changed',
                'description' => 'Default administrative passwords are not in use.',
                'categories' => ['security' => 3],
                'severity' => 'major',
                'finding' => 'A default or weak administrative password may still be in use.',
                'recommendation' => 'Change default credentials and record where privileged credentials are managed.',
            ],
            'firmware_current' => [
                'label' => 'Firmware current',
                'description' => 'Network device firmware is maintained.',
                'categories' => ['security' => 2, 'resilience' => 1],
                'severity' => 'major',
                'finding' => 'Network device firmware is not current.',
                'recommendation' => 'Update firmware and define a review cadence.',
            ],
            'guest_network_isolated' => [
                'label' => 'Guest network isolated',
                'description' => 'Guest or patient Wi-Fi cannot reach practice systems.',
                'categories' => ['security' => 3],
                'severity' => 'major',
                'finding' => 'Guest connectivity is not isolated from practice systems.',
                'recommendation' => 'Separate guest Wi-Fi from clinical and administrative assets.',
            ],
            'wifi_encryption' => [
                'label' => 'Wi-Fi encryption',
                'description' => 'Wireless access uses strong encryption and a controlled passphrase.',
                'categories' => ['security' => 2],
                'severity' => 'major',
                'finding' => 'Wireless access protection is weak or undocumented.',
                'recommendation' => 'Use strong Wi-Fi encryption and manage access credentials.',
            ],
            'backup_schedule' => [
                'label' => 'Backup schedule',
                'description' => 'Critical systems are backed up on a defined schedule.',
                'categories' => ['resilience' => 3, 'documentation' => 1],
                'severity' => 'major',
                'finding' => 'Backups are not scheduled or documented.',
                'recommendation' => 'Define backup frequency, scope, owner, and monitoring evidence.',
            ],
            'encrypted_backup' => [
                'label' => 'Encrypted backup',
                'description' => 'Backup data is encrypted at rest and in transit.',
                'categories' => ['security' => 2, 'resilience' => 1],
                'severity' => 'major',
                'finding' => 'Backup data is not encrypted.',
                'recommendation' => 'Encrypt backups and protect recovery keys.',
            ],
            'restore_test' => [
                'label' => 'Restore tested',
                'description' => 'Recovery has been tested and evidence is available.',
                'categories' => ['resilience' => 3, 'audit' => 2],
                'severity' => 'major',
                'finding' => 'Restore capability has not been proven.',
                'recommendation' => 'Run a restore test and keep results for audit.',
            ],
            'offline_or_immutable_copy' => [
                'label' => 'Offline or immutable copy',
                'description' => 'At least one backup copy is protected from ransomware or accidental deletion.',
                'categories' => ['resilience' => 3, 'security' => 1],
                'severity' => 'major',
                'finding' => 'Backups may be altered or deleted by the same incident affecting production.',
                'recommendation' => 'Keep an offline, immutable, or separately controlled backup copy.',
            ],
            'physical_lock' => [
                'label' => 'Physical lock',
                'description' => 'Physical records or equipment are secured when unattended.',
                'categories' => ['security' => 2],
                'severity' => 'major',
                'finding' => 'Physical access is not adequately restricted.',
                'recommendation' => 'Use locks and restrict access to authorized staff.',
            ],
            'retention_policy' => [
                'label' => 'Retention policy',
                'description' => 'Retention and deletion expectations are defined.',
                'categories' => ['documentation' => 2, 'audit' => 1],
                'severity' => 'minor',
                'finding' => 'Retention and deletion rules are not documented.',
                'recommendation' => 'Document retention periods and disposal approvals.',
            ],
            'access_list' => [
                'label' => 'Access list',
                'description' => 'Authorized access to physical records is known.',
                'categories' => ['security' => 1, 'documentation' => 1, 'audit' => 1],
                'severity' => 'minor',
                'finding' => 'Access to physical records is not traceable.',
                'recommendation' => 'Record who may access records and why.',
            ],
            'clean_desk' => [
                'label' => 'Clean desk practice',
                'description' => 'Sensitive documents are not left exposed.',
                'categories' => ['security' => 1],
                'severity' => 'minor',
                'finding' => 'Sensitive documents may be left visible.',
                'recommendation' => 'Introduce clean desk expectations and periodic checks.',
            ],
            'asset_inventory' => [
                'label' => 'Asset inventory',
                'description' => 'Information assets and supporting systems are listed.',
                'categories' => ['documentation' => 3, 'audit' => 2],
                'severity' => 'major',
                'finding' => 'The asset inventory is incomplete.',
                'recommendation' => 'List systems, devices, services, information assets, owners, and criticality.',
            ],
            'risk_register' => [
                'label' => 'Risk register',
                'description' => 'Risks are identified, assessed, and linked to treatment choices.',
                'categories' => ['documentation' => 3, 'audit' => 2, 'resilience' => 1],
                'severity' => 'major',
                'finding' => 'Risk assessment evidence is missing.',
                'recommendation' => 'Record risks, likelihood, impact, treatment, owners, and review dates.',
            ],
            'soa_prepared' => [
                'label' => 'Statement of Applicability',
                'description' => 'Selected and excluded controls are justified.',
                'categories' => ['documentation' => 3, 'audit' => 3],
                'severity' => 'major',
                'finding' => 'The control selection rationale is missing.',
                'recommendation' => 'Prepare a Statement of Applicability with inclusion, exclusion, and implementation status.',
            ],
            'incident_procedure' => [
                'label' => 'Incident procedure',
                'description' => 'Staff know how to report and handle information security incidents.',
                'categories' => ['resilience' => 2, 'documentation' => 2, 'audit' => 1],
                'severity' => 'major',
                'finding' => 'Incident handling is not defined.',
                'recommendation' => 'Define reporting, triage, escalation, communication, and lessons learned steps.',
            ],
            'internal_audit_plan' => [
                'label' => 'Internal audit plan',
                'description' => 'The practice has planned and recorded internal audit activity.',
                'categories' => ['audit' => 3, 'documentation' => 1],
                'severity' => 'major',
                'finding' => 'Internal audit evidence is not available.',
                'recommendation' => 'Plan internal audits, record scope, findings, and corrective actions.',
            ],
            'management_review_record' => [
                'label' => 'Management review',
                'description' => 'Leadership reviews ISMS performance and improvement actions.',
                'categories' => ['audit' => 3, 'documentation' => 1],
                'severity' => 'major',
                'finding' => 'Management review evidence is missing.',
                'recommendation' => 'Record leadership review of risks, incidents, audits, resources, and improvement actions.',
            ],
            'staff_training' => [
                'label' => 'Staff training',
                'description' => 'Staff have completed basic security and privacy handling training.',
                'categories' => ['security' => 1, 'documentation' => 1, 'audit' => 1],
                'severity' => 'minor',
                'finding' => 'Training evidence is incomplete.',
                'recommendation' => 'Train staff and keep completion evidence.',
            ],
        ];
    }

    /**
     * @return list<array<string,mixed>>
     */
    public static function officeObjects(): array
    {
        return [
            [
                'object_key' => 'reception_pc',
                'object_type' => 'workstation',
                'display_name' => 'Reception PC',
                'x' => 3,
                'y' => 3,
                'width' => 3,
                'height' => 2,
                'sort_layer' => 20,
                'controls' => ['documented_owner', 'mfa_enabled', 'disk_encryption', 'patching_current', 'screen_lock', 'least_privilege'],
                'initial' => ['screen_lock' => true, 'patching_current' => true],
            ],
            [
                'object_key' => 'doctor_pc',
                'object_type' => 'workstation',
                'display_name' => 'Doctor PC',
                'x' => 10,
                'y' => 4,
                'width' => 3,
                'height' => 2,
                'sort_layer' => 20,
                'controls' => ['documented_owner', 'mfa_enabled', 'disk_encryption', 'patching_current', 'screen_lock', 'least_privilege'],
                'initial' => ['screen_lock' => true, 'disk_encryption' => true],
            ],
            [
                'object_key' => 'nurse_laptop',
                'object_type' => 'laptop',
                'display_name' => 'Nurse Laptop',
                'x' => 17,
                'y' => 4,
                'width' => 3,
                'height' => 2,
                'sort_layer' => 20,
                'controls' => ['documented_owner', 'mfa_enabled', 'disk_encryption', 'patching_current', 'screen_lock', 'least_privilege'],
                'initial' => ['screen_lock' => true],
            ],
            [
                'object_key' => 'ehr_cloud',
                'object_type' => 'cloud_service',
                'display_name' => 'Cloud EHR',
                'x' => 22,
                'y' => 2,
                'width' => 4,
                'height' => 3,
                'sort_layer' => 30,
                'controls' => ['documented_owner', 'supplier_reviewed', 'contract_dpa', 'mfa_enabled', 'access_review', 'backup_export_plan'],
                'initial' => ['mfa_enabled' => true],
            ],
            [
                'object_key' => 'network_router',
                'object_type' => 'network',
                'display_name' => 'Router and Wi-Fi',
                'x' => 22,
                'y' => 8,
                'width' => 3,
                'height' => 2,
                'sort_layer' => 20,
                'controls' => ['documented_owner', 'admin_password_changed', 'firmware_current', 'guest_network_isolated', 'wifi_encryption'],
                'initial' => ['admin_password_changed' => true, 'wifi_encryption' => true],
            ],
            [
                'object_key' => 'backup_nas',
                'object_type' => 'backup',
                'display_name' => 'Backup NAS',
                'x' => 22,
                'y' => 12,
                'width' => 3,
                'height' => 2,
                'sort_layer' => 20,
                'controls' => ['documented_owner', 'backup_schedule', 'encrypted_backup', 'restore_test', 'offline_or_immutable_copy'],
                'initial' => ['backup_schedule' => true],
            ],
            [
                'object_key' => 'printer',
                'object_type' => 'printer',
                'display_name' => 'Shared Printer',
                'x' => 4,
                'y' => 11,
                'width' => 3,
                'height' => 2,
                'sort_layer' => 20,
                'controls' => ['documented_owner', 'secure_print', 'located_supervised', 'disposal_procedure'],
                'initial' => ['located_supervised' => true],
            ],
            [
                'object_key' => 'records_cabinet',
                'object_type' => 'records',
                'display_name' => 'Records Cabinet',
                'x' => 10,
                'y' => 12,
                'width' => 3,
                'height' => 3,
                'sort_layer' => 20,
                'controls' => ['documented_owner', 'physical_lock', 'retention_policy', 'access_list', 'clean_desk'],
                'initial' => ['physical_lock' => true],
            ],
            [
                'object_key' => 'isms_binder',
                'object_type' => 'documentation',
                'display_name' => 'ISMS Binder',
                'x' => 16,
                'y' => 12,
                'width' => 3,
                'height' => 3,
                'sort_layer' => 20,
                'controls' => ['asset_inventory', 'risk_register', 'soa_prepared', 'incident_procedure', 'internal_audit_plan', 'management_review_record', 'staff_training'],
                'initial' => [],
            ],
            [
                'object_key' => 'shred_console',
                'object_type' => 'disposal',
                'display_name' => 'Shred Console',
                'x' => 4,
                'y' => 15,
                'width' => 2,
                'height' => 2,
                'sort_layer' => 20,
                'controls' => ['documented_owner', 'disposal_procedure', 'staff_training'],
                'initial' => [],
            ],
        ];
    }

    /**
     * @return list<array<string,mixed>>
     */
    public static function assetInventoryItems(): array
    {
        return [
            [
                'asset_key' => 'patient_records',
                'object_key' => 'records_cabinet',
                'name' => 'Patient records',
                'asset_type' => 'information',
                'owner' => 'Practice Manager',
                'information_classification' => 'confidential',
                'criticality' => 'high',
                'status' => 'draft',
                'notes' => 'Includes paper and exported electronic records used for patient care.',
            ],
            [
                'asset_key' => 'ehr_service',
                'object_key' => 'ehr_cloud',
                'name' => 'Cloud EHR service',
                'asset_type' => 'cloud_service',
                'owner' => 'Practice Manager',
                'information_classification' => 'confidential',
                'criticality' => 'high',
                'status' => 'draft',
                'notes' => 'Primary clinical record system and supplier dependency.',
            ],
            [
                'asset_key' => 'reception_workstation',
                'object_key' => 'reception_pc',
                'name' => 'Reception workstation',
                'asset_type' => 'endpoint',
                'owner' => 'Reception Lead',
                'information_classification' => 'internal',
                'criticality' => 'medium',
                'status' => 'draft',
                'notes' => 'Used for scheduling, intake, and patient communication.',
            ],
            [
                'asset_key' => 'clinical_workstations',
                'object_key' => 'doctor_pc',
                'name' => 'Clinical workstations',
                'asset_type' => 'endpoint',
                'owner' => 'Medical Director',
                'information_classification' => 'confidential',
                'criticality' => 'high',
                'status' => 'draft',
                'notes' => 'Doctor and nurse endpoints used during consultations.',
            ],
            [
                'asset_key' => 'network_infrastructure',
                'object_key' => 'network_router',
                'name' => 'Router and wireless network',
                'asset_type' => 'network',
                'owner' => 'IT Support',
                'information_classification' => 'internal',
                'criticality' => 'high',
                'status' => 'draft',
                'notes' => 'Provides connectivity for clinical and administrative systems.',
            ],
            [
                'asset_key' => 'backup_repository',
                'object_key' => 'backup_nas',
                'name' => 'Backup repository',
                'asset_type' => 'backup',
                'owner' => 'IT Support',
                'information_classification' => 'confidential',
                'criticality' => 'high',
                'status' => 'draft',
                'notes' => 'Stores recoverable copies of critical records and configuration.',
            ],
            [
                'asset_key' => 'printing_workflow',
                'object_key' => 'printer',
                'name' => 'Printing workflow',
                'asset_type' => 'process',
                'owner' => 'Reception Lead',
                'information_classification' => 'confidential',
                'criticality' => 'medium',
                'status' => 'draft',
                'notes' => 'Covers printed patient information, collection, and disposal.',
            ],
            [
                'asset_key' => 'isms_documentation',
                'object_key' => 'isms_binder',
                'name' => 'ISMS documentation set',
                'asset_type' => 'documentation',
                'owner' => 'Practice Manager',
                'information_classification' => 'internal',
                'criticality' => 'medium',
                'status' => 'draft',
                'notes' => 'Policies, risk decisions, audit records, and improvement evidence.',
            ],
        ];
    }

    /**
     * @return list<array<string,mixed>>
     */
    public static function riskRegisterItems(): array
    {
        return [
            [
                'risk_key' => 'unauthorized_ehr_access',
                'object_key' => 'ehr_cloud',
                'title' => 'Unauthorized access to Cloud EHR',
                'owner' => 'Practice Manager',
                'likelihood' => 3,
                'impact' => 5,
                'treatment_status' => 'identified',
                'treatment_summary' => 'MFA, access review, supplier commitments, and account lifecycle controls are expected.',
            ],
            [
                'risk_key' => 'lost_clinical_endpoint',
                'object_key' => 'nurse_laptop',
                'title' => 'Loss or theft of a clinical endpoint',
                'owner' => 'IT Support',
                'likelihood' => 3,
                'impact' => 4,
                'treatment_status' => 'identified',
                'treatment_summary' => 'Disk encryption, screen lock, least privilege, and inventory evidence are expected.',
            ],
            [
                'risk_key' => 'ransomware_recovery_failure',
                'object_key' => 'backup_nas',
                'title' => 'Ransomware prevents recovery of patient records',
                'owner' => 'IT Support',
                'likelihood' => 3,
                'impact' => 5,
                'treatment_status' => 'identified',
                'treatment_summary' => 'Backups, restore tests, and an offline or immutable copy are expected.',
            ],
            [
                'risk_key' => 'exposed_printouts',
                'object_key' => 'printer',
                'title' => 'Patient information exposed through printouts',
                'owner' => 'Reception Lead',
                'likelihood' => 4,
                'impact' => 3,
                'treatment_status' => 'identified',
                'treatment_summary' => 'Secure print, supervised collection, and disposal procedure are expected.',
            ],
            [
                'risk_key' => 'network_misconfiguration',
                'object_key' => 'network_router',
                'title' => 'Network misconfiguration exposes practice systems',
                'owner' => 'IT Support',
                'likelihood' => 3,
                'impact' => 4,
                'treatment_status' => 'identified',
                'treatment_summary' => 'Firmware maintenance, guest isolation, and admin credential control are expected.',
            ],
            [
                'risk_key' => 'audit_evidence_gap',
                'object_key' => 'isms_binder',
                'title' => 'Controls cannot be verified during audit',
                'owner' => 'Practice Manager',
                'likelihood' => 4,
                'impact' => 4,
                'treatment_status' => 'identified',
                'treatment_summary' => 'Evidence ownership, internal audit records, and management review records are expected.',
            ],
        ];
    }

    /**
     * @return list<array<string,mixed>>
     */
    public static function evidenceItems(): array
    {
        return [
            [
                'evidence_key' => 'asset_inventory_export',
                'object_key' => 'isms_binder',
                'title' => 'Current asset inventory',
                'evidence_type' => 'inventory',
                'expected_evidence' => 'A dated inventory with owners, classification, criticality, and supporting assets.',
                'owner' => 'Practice Manager',
                'status' => 'missing',
                'notes' => '',
            ],
            [
                'evidence_key' => 'risk_register_review',
                'object_key' => 'isms_binder',
                'title' => 'Risk register review record',
                'evidence_type' => 'risk',
                'expected_evidence' => 'A risk register showing likelihood, impact, treatment, owner, and review status.',
                'owner' => 'Practice Manager',
                'status' => 'missing',
                'notes' => '',
            ],
            [
                'evidence_key' => 'statement_of_applicability',
                'object_key' => 'isms_binder',
                'title' => 'Statement of Applicability baseline',
                'evidence_type' => 'soa',
                'expected_evidence' => 'A control applicability record with inclusion, exclusion, and implementation rationale.',
                'owner' => 'Practice Manager',
                'status' => 'missing',
                'notes' => '',
            ],
            [
                'evidence_key' => 'ehr_access_review',
                'object_key' => 'ehr_cloud',
                'title' => 'Cloud EHR access review',
                'evidence_type' => 'access_review',
                'expected_evidence' => 'A recent review of active EHR users, roles, privileged accounts, and removals.',
                'owner' => 'Practice Manager',
                'status' => 'missing',
                'notes' => '',
            ],
            [
                'evidence_key' => 'supplier_review_ehr',
                'object_key' => 'ehr_cloud',
                'title' => 'Cloud EHR supplier review',
                'evidence_type' => 'supplier',
                'expected_evidence' => 'Supplier security, continuity, support, and contract evidence for the EHR service.',
                'owner' => 'Practice Manager',
                'status' => 'missing',
                'notes' => '',
            ],
            [
                'evidence_key' => 'backup_restore_test',
                'object_key' => 'backup_nas',
                'title' => 'Backup restore test result',
                'evidence_type' => 'resilience',
                'expected_evidence' => 'A dated restore test with scope, result, issues, and follow-up actions.',
                'owner' => 'IT Support',
                'status' => 'missing',
                'notes' => '',
            ],
            [
                'evidence_key' => 'incident_procedure_record',
                'object_key' => 'isms_binder',
                'title' => 'Incident procedure and reporting route',
                'evidence_type' => 'procedure',
                'expected_evidence' => 'A practical incident procedure with reporting, triage, escalation, and lessons learned.',
                'owner' => 'Practice Manager',
                'status' => 'missing',
                'notes' => '',
            ],
            [
                'evidence_key' => 'internal_audit_record',
                'object_key' => 'isms_binder',
                'title' => 'Internal audit record',
                'evidence_type' => 'audit',
                'expected_evidence' => 'Internal audit scope, observations, findings, corrective actions, and closure status.',
                'owner' => 'Practice Manager',
                'status' => 'missing',
                'notes' => '',
            ],
        ];
    }

    /**
     * @return list<array<string,mixed>>
     */
    public static function eventScenarios(): array
    {
        return [
            [
                'event_key' => 'phishing_ehr_password',
                'object_key' => 'ehr_cloud',
                'title' => 'Phishing attempt against EHR access',
                'description' => 'A receptionist reports an email asking them to confirm their Cloud EHR password on a lookalike page.',
                'severity' => 'major',
                'status' => 'available',
                'trigger_text' => 'Start the phishing event and decide what evidence and corrective action are needed.',
                'lesson_text' => 'The office needs MFA, staff reporting behavior, access review evidence, and a clear incident route.',
                'required_controls' => ['mfa_enabled', 'access_review', 'incident_procedure'],
                'required_evidence' => ['ehr_access_review', 'incident_procedure_record'],
                'corrective_action_title' => 'Close phishing event gaps for EHR access',
                'owner' => 'Practice Manager',
            ],
            [
                'event_key' => 'lost_nurse_laptop',
                'object_key' => 'nurse_laptop',
                'title' => 'Lost nurse laptop',
                'description' => 'A nurse cannot find a laptop after a home visit and the practice must judge exposure and recovery steps.',
                'severity' => 'major',
                'status' => 'available',
                'trigger_text' => 'Start the lost-device event and verify whether the practice can prove containment.',
                'lesson_text' => 'Portable endpoint incidents need encryption evidence, inventory ownership, and defined reporting.',
                'required_controls' => ['disk_encryption', 'screen_lock', 'asset_inventory', 'incident_procedure'],
                'required_evidence' => ['asset_inventory_export', 'incident_procedure_record'],
                'corrective_action_title' => 'Prove containment for lost clinical endpoint',
                'owner' => 'IT Support',
            ],
            [
                'event_key' => 'backup_restore_failure',
                'object_key' => 'backup_nas',
                'title' => 'Backup restore failure',
                'description' => 'A restore test fails because the backup job ran but the recovery procedure was never verified.',
                'severity' => 'major',
                'status' => 'available',
                'trigger_text' => 'Start the recovery event and decide what must be corrected before audit.',
                'lesson_text' => 'Resilience depends on restore evidence, not only backup configuration.',
                'required_controls' => ['backup_schedule', 'encrypted_backup', 'restore_test', 'offline_or_immutable_copy'],
                'required_evidence' => ['backup_restore_test', 'risk_register_review'],
                'corrective_action_title' => 'Make backup recovery evidence audit-ready',
                'owner' => 'IT Support',
            ],
        ];
    }

    /**
     * @return array<string,mixed>
     */
    public static function scenario(): array
    {
        return [
            'key' => 'small_physician_office',
            'name' => 'Small Physician Office',
            'map_width' => 28,
            'map_height' => 18,
            'tile_size' => 1,
            'objective' => 'Prepare a small practice for a credible ISO/IEC 27001-style certification audit.',
        ];
    }
}
